import { sqliteTable, text, integer, index } from "drizzle-orm/sqlite-core";

export const evaluationRecords = sqliteTable(
  "evaluation_records",
  {
    id: text("id").primaryKey(),
    submittedAt: text("submitted_at").notNull(),
    storeUrl: text("store_url").notNull().default(""),
    gameName: text("game_name").notNull().default(""),
    steamGameName: text("steam_game_name").notNull().default(""),
    appid: text("appid").notNull().default(""),
    phone: text("phone").notNull().default(""),
    visitorId: text("visitor_id").notNull().default(""),
    requirements: text("requirements").notNull().default(""),
    result: text("result").notNull().default("fail"),
    passed: integer("passed", { mode: "boolean" }).notNull().default(false),
    paymentClicked: integer("payment_clicked", { mode: "boolean" }).notNull().default(false),
    paymentClickedAt: text("payment_clicked_at").notNull().default(""),
    reason: text("reason").notNull().default(""),
    resultTitle: text("result_title").notNull().default(""),
    resultDetail: text("result_detail").notNull().default(""),
    autoPassed: integer("auto_passed", { mode: "boolean" }),
    manualPassed: integer("manual_passed", { mode: "boolean" }),
    manualReason: text("manual_reason").notNull().default(""),
    appType: text("app_type").notNull().default(""),
    technologies: text("technologies").notNull().default(""),
    releaseDate: text("release_date").notNull().default(""),
    categories: text("categories").notNull().default(""),
    tag: text("tag").notNull().default(""),
    screenshots: text("screenshots").notNull().default(""),
    createdAt: text("created_at").notNull(),
  },
  (table) => [
    index("evaluation_records_submitted_at_idx").on(table.submittedAt),
    index("evaluation_records_phone_idx").on(table.phone),
    index("evaluation_records_visitor_id_idx").on(table.visitorId),
    index("evaluation_records_appid_idx").on(table.appid),
    index("evaluation_records_game_name_idx").on(table.gameName),
  ],
);

export const steamGameQueries = sqliteTable(
  "steam_game_queries",
  {
    id: text("id").primaryKey(),
    appid: text("appid").notNull(),
    gameNameEn: text("game_name_en").notNull().default(""),
    gameNameZh: text("game_name_zh").notNull().default(""),
    appType: text("app_type").notNull().default(""),
    technologies: text("technologies").notNull().default(""),
    releaseDate: text("release_date").notNull().default(""),
    categories: text("categories").notNull().default(""),
    tag: text("tag").notNull().default(""),
    screenshots: text("screenshots").notNull().default(""),
    playersRightNow: text("players_right_now").notNull().default(""),
    peak24h: text("peak_24h").notNull().default(""),
    allTimePeak: text("all_time_peak").notNull().default(""),
    languages: text("languages").notNull().default(""),
    clientStatus: text("client_status").notNull().default(""),
    clientDevelopmentStatus: text("client_development_status").notNull().default(""),
    autoPassed: integer("auto_passed", { mode: "boolean" }).notNull().default(false),
    finalPassed: integer("final_passed", { mode: "boolean" }).notNull().default(false),
    manualPassed: integer("manual_passed", { mode: "boolean" }),
    manualReason: text("manual_reason").notNull().default(""),
    resultTitle: text("result_title").notNull().default(""),
    resultDetail: text("result_detail").notNull().default(""),
    reason: text("reason").notNull().default(""),
    rawJson: text("raw_json").notNull().default(""),
    queriedAt: text("queried_at").notNull(),
  },
  (table) => [
    index("steam_game_queries_appid_idx").on(table.appid),
    index("steam_game_queries_queried_at_idx").on(table.queriedAt),
  ],
);

export const steamGameOverrides = sqliteTable("steam_game_overrides", {
  appid: text("appid").primaryKey(),
  manualPassed: integer("manual_passed", { mode: "boolean" }),
  manualReason: text("manual_reason").notNull().default(""),
  updatedAt: text("updated_at").notNull(),
});

export const pageExposures = sqliteTable(
  "page_exposures",
  {
    id: text("id").primaryKey(),
    visitorId: text("visitor_id").notNull(),
    phone: text("phone").notNull().default(""),
    path: text("path").notNull().default(""),
    referrer: text("referrer").notNull().default(""),
    userAgent: text("user_agent").notNull().default(""),
    createdAt: text("created_at").notNull(),
  },
  (table) => [
    index("page_exposures_created_at_idx").on(table.createdAt),
    index("page_exposures_visitor_id_idx").on(table.visitorId),
    index("page_exposures_phone_idx").on(table.phone),
  ],
);
